# Generated by Django 5.1.5 on 2025-01-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Course',
        ),
    ]
