# Generated by Django 5.1.5 on 2025-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_chapter_course_alter_lesson_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, default='video/examples.mp4', null=True, upload_to='video/'),
        ),
    ]
