# Generated by Django 5.1.5 on 2025-04-16 22:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lesson_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'course')},
        ),
        migrations.AddField(
            model_name='progress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.course'),
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.progress')),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_chapters',
            field=models.ManyToManyField(blank=True, through='courses.ChapterProgress', to='courses.chapter'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.progress')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(default=dict)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.progress')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quiz')),
            ],
            options={
                'ordering': ['-attempt_number'],
            },
        ),
        migrations.AddField(
            model_name='progress',
            name='quiz_attempts',
            field=models.ManyToManyField(blank=True, through='courses.QuizAttempt', to='courses.quiz'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'course'], name='courses_pro_user_id_aa1c08_idx'),
        ),
        migrations.RemoveField(
            model_name='progress',
            name='completed_lessons',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='quiz_scores',
        ),
        migrations.AlterUniqueTogether(
            name='chapterprogress',
            unique_together={('progress', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('progress', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('progress', 'quiz', 'attempt_number')},
        ),
    ]
