# Generated by Django 5.1.5 on 2025-04-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_progress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, through='courses.LessonProgress', to='courses.lesson'),
        ),
    ]
